name: Desplegar Código de Lambdas (Laboratorio AWS)

on:
  push:
    branches:
      - master # O 'main', según tu rama

# Define los nombres de los secretos que usaremos
env:
  LAB_AWS_ACCESS_KEY_ID: ${{ secrets.LAB_AWS_ACCESS_KEY_ID }}
  LAB_AWS_SECRET_ACCESS_KEY: ${{ secrets.LAB_AWS_SECRET_ACCESS_KEY }}
  LAB_AWS_SESSION_TOKEN: ${{ secrets.LAB_AWS_SESSION_TOKEN }}

jobs:
  deploy-lambda-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # --- Configurando credenciales ---
      - name: Configure AWS Credentials (con Token de Sesión)
        uses: aws-actions/configure-aws-credentials@v4 # Usamos v4, la más actual
        with:
          aws-access-key-id: ${{ env.LAB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.LAB_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.LAB_AWS_SESSION_TOKEN }}
          aws-region: us-east-1 # ¡Asegúrate de que esta es tu región del lab!

      # --- Pasos de Despliegue (Corregidos con tus nombres de AWS) ---
      - name: Deploy s3_file_event
        run: |
          cd s3_file_event
          zip -r ../lambda1.zip .
          cd ..
          aws lambda update-function-code --function-name s3_file_event --zip-file fileb://lambda1.zip

      - name: Deploy get_image_metadata
        run: |
          cd get_image_metadata
          zip -r ../lambda2.zip .
          cd ..
          aws lambda update-function-code --function-name get_image_metadata --zip-file fileb://lambda2.zip

      - name: Despliegue completado
        run: echo "¡Código de Lambdas actualizado exitosamente!"